Phase 1: Dataset preparation

Step 1: Import Required Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

Step 2: Load Dataset

In [2]:
df=pd.read_excel("Movie_Recommendation_System.xlsx")

Step 3: Display Dataset

In [3]:
df.head()

,User_ID,Movie_ID,Movie_Title,Genre,Release_Year,Rating,Number_of_Ratings,Runtime_Minutes,Language,Age_Group
0,157,1052,Beyond the Stars,Horror,2013,8.0,50813,101,Korean,13-17
1,47,1093,Beyond the Stars,Horror,2015,6.5,20490,113,Hindi,13-17
2,173,1015,The Lost Kingdom,Sci-Fi,2022,4.7,75503,128,English,35-44
3,130,1072,The Silent House,Sci-Fi,2024,7.9,58566,80,Hindi,45+
4,95,1061,The Silent House,Comedy,2019,7.6,4081,152,Spanish,25-34

In [4]:
df.tail

<bound method NDFrame.tail of       User_ID  Movie_ID       Movie_Title     Genre  Release_Year  Rating  \
0         157      1052  Beyond the Stars    Horror          2013     8.0
1          47      1093  Beyond the Stars    Horror          2015     6.5
2         173      1015  The Lost Kingdom    Sci-Fi          2022     4.7
3         130      1072  The Silent House    Sci-Fi          2024     7.9
4          95      1061  The Silent House    Comedy          2019     7.6
...       ...       ...               ...       ...           ...     ...
1195      220      1056      Future World    Action          2025     7.3
1196      223      1015     Final Verdict   Romance          2014     NaN
1197      136      1029    Love in Winter    Sci-Fi          2016     6.2
1198      256      1008       Digital Age  Thriller          2014     6.9
1199       49      1005     Wild Frontier    Action          2019     8.5

      Number_of_Ratings  Runtime_Minutes  Language Age_Group
0                 50813              101    Korean     13-17
1                 20490              113     Hindi     13-17
2                 75503              128   English     35-44
3                 58566               80     Hindi       45+
4                  4081              152   Spanish     25-34
...                 ...              ...       ...       ...
1195              25418              102    French     35-44
1196              33834              147    French     18-24
1197              82327              100    French     35-44
1198              18622              180    French       45+
1199              11756              122  Japanese     18-24

[1200 rows x 10 columns]>

Step 4: Shape of Dataset

In [5]:
df.shape

(1200, 10)

Step 5: Column Names

In [6]:
df.columns

Index(['User_ID', 'Movie_ID', 'Movie_Title', 'Genre', 'Release_Year', 'Rating',
       'Number_of_Ratings', 'Runtime_Minutes', 'Language', 'Age_Group'],
      dtype='str')

Step 6: Dataset Information

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User_ID            1200 non-null   int64
 1   Movie_ID           1200 non-null   int64
 2   Movie_Title        1200 non-null   str
 3   Genre              1188 non-null   str
 4   Release_Year       1200 non-null   int64
 5   Rating             1188 non-null   float64
 6   Number_of_Ratings  1200 non-null   int64
 7   Runtime_Minutes    1200 non-null   int64
 8   Language           1188 non-null   str
 9   Age_Group          1200 non-null   str
dtypes: float64(1), int64(5), str(4)
memory usage: 130.1 KB

Step 7: Statistical Summary

In [8]:
df.describe()

,User_ID,Movie_ID,Release_Year,Rating,Number_of_Ratings,Runtime_Minutes
count,1200.000000,1200.000000,1200.000000,1188.000000,1200.000000,1200.000000
mean,150.041667,1049.659167,2017.765833,7.075168,49427.579167,130.548333
std,87.473928,29.511022,4.562713,1.094867,29504.172691,28.610251
min,1.000000,1001.000000,2010.000000,3.700000,128.000000,80.000000
25%,76.000000,1024.000000,2014.000000,6.300000,23374.250000,105.000000
50%,150.000000,1050.000000,2018.000000,7.100000,48194.000000,132.000000
75%,226.000000,1075.000000,2022.000000,7.800000,75891.000000,155.000000
max,300.000000,1100.000000,2025.000000,10.000000,99962.000000,180.000000

Step 8: Check Data Types

In [9]:
df.dtypes

User_ID                int64
Movie_ID               int64
Movie_Title              str
Genre                    str
Release_Year           int64
Rating               float64
Number_of_Ratings      int64
Runtime_Minutes        int64
Language                 str
Age_Group                str
dtype: object

Step 9: Check Missing Values

In [10]:
df.isnull().sum()

User_ID               0
Movie_ID              0
Movie_Title           0
Genre                12
Release_Year          0
Rating               12
Number_of_Ratings     0
Runtime_Minutes       0
Language             12
Age_Group             0
dtype: int64

In [11]:
(df.isnull().sum()/len(df))*100

User_ID              0.0
Movie_ID             0.0
Movie_Title          0.0
Genre                1.0
Release_Year         0.0
Rating               1.0
Number_of_Ratings    0.0
Runtime_Minutes      0.0
Language             1.0
Age_Group            0.0
dtype: float64

Step 10: Check Duplicate Records

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df[df.duplicated()]

Empty DataFrame
Columns: [User_ID, Movie_ID, Movie_Title, Genre, Release_Year, Rating, Number_of_Ratings, Runtime_Minutes, Language, Age_Group]
Index: []

In [14]:
df =df.dropna(subset=['Movie_ID', 'Movie_Title'])  
df= df.dropna(subset=['User_ID', 'Rating'])

In [15]:
df = df[(df['Rating'] >= 1) & (df['Rating'] <= 5)]

In [16]:
user_movie_matrix = df.pivot_table(index='User_ID', columns='Movie_ID', values='Rating').fillna(0)

In [17]:
user_sim_matrix = cosine_similarity(user_movie_matrix)
user_sim_df = pd.DataFrame(user_sim_matrix, index=user_movie_matrix.index, columns=user_movie_matrix.index)

In [18]:
target_user = 38

In [19]:
sim_users = user_sim_df[target_user].sort_values(ascending=False)
sim_users = sim_users.drop(target_user)

In [20]:
sim_users

User_ID
9      0.0
10     0.0
12     0.0
23     0.0
60     0.0
61     0.0
69     0.0
73     0.0
80     0.0
89     0.0
101    0.0
104    0.0
109    0.0
117    0.0
120    0.0
121    0.0
128    0.0
136    0.0
160    0.0
161    0.0
167    0.0
173    0.0
181    0.0
188    0.0
193    0.0
226    0.0
236    0.0
250    0.0
251    0.0
268    0.0
292    0.0
293    0.0
294    0.0
Name: 38, dtype: float64

In [21]:
movies_seen = user_movie_matrix.loc[target_user][user_movie_matrix.loc[target_user] > 0].index.tolist()

In [22]:
recommendations = []
for sim_user in sim_users.index:
    high_rated_movies = user_movie_matrix.loc[sim_user][user_movie_matrix.loc[sim_user] >= 4].index.tolist()
    for movie in high_rated_movies:
        if (movie not in movies_seen) and (movie not in recommendations):
            recommendations.append(movie)
    if len(recommendations) >= 5:
        break

In [23]:
recommended_titles = df[df['Movie_ID'].isin(recommendations)][['Movie_ID', 'Movie_Title']]
print("Top recommended movies for user", target_user)
print(recommended_titles)

Top recommended movies for user 38
     Movie_ID     Movie_Title
233      1053    Secret Agent
264      1067    Code Breaker
377      1053    Secret Agent
443      1022    Code Breaker
697      1013  Parallel Lives
878      1079    Broken Roads
895      1053    Hidden Truth

In [24]:
print("Most similar users to", target_user)
print(sim_users.head(3))

Most similar users to 38
User_ID
9     0.0
10    0.0
12    0.0
Name: 38, dtype: float64

In [25]:
print(type(df))
print(type(user_movie_matrix))

<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>

In [26]:
for movie in recommendations:
    liked_by = []
    # Check among top 10 similar users
    for sim_user in sim_users.index[:10]:
        Rating = user_movie_matrix.loc[sim_user, movie]
        if Rating >= 4:
            liked_by.append(sim_user)
    title = df[df['Movie_ID'] == movie]['Movie_Title'].values[0]
    print(f"Movie: {title} (ID: {movie}) liked by users: {liked_by}")

Movie: Broken Roads (ID: 1079) liked by users: [9]
Movie: Parallel Lives (ID: 1013) liked by users: [10]
Movie: Code Breaker (ID: 1067) liked by users: [12]
Movie: Code Breaker (ID: 1022) liked by users: [23]
Movie: Secret Agent (ID: 1053) liked by users: [60, 61]

In [27]:
user_movie_matrix.to_csv("user_movie_matrix.csv")
df.to_csv("movies.csv", index=False)
user_sim_df.to_csv("user_sim_df.csv")

In [28]:

import joblib
import os

# Create folder to store model
os.makedirs("models", exist_ok=True)

# Save model components
model_data = {
    "user_similarity": user_sim_df,
    "user_movie_matrix": user_movie_matrix
}

joblib.dump(model_data, "movie_recommendation_model.pkl")

print("Model saved successfully!")

Model saved successfully!